//@version=3
strategy("News", overlay=true)
atr_period = 7

inplTakeProfit = high + ( atr(atr_period) * 2 )
inplEntry = high
inplStopLoss = hl2 - atr(atr_period)
inplTrailStop = na
inplTrailOffset = na
inpsTakeProfit = low - ( atr(atr_period) * 2 )
inpsEntry = low
inpsStopLoss = hl2 + atr(atr_period)
inpsTrailStop = na
inpsTrailOffset = na

if (close > open)
    inplStopLoss = close + atr(atr_period)
    inpsStopLoss = open - atr(atr_period)

if (open > close)
    inplStopLoss = open + atr(atr_period)
    inpsStopLoss = close - atr(atr_period)

plotbar(inplEntry, inplTakeProfit, inplStopLoss, inplEntry, title='L', color = green)
plotbar(inpsEntry, inpsStopLoss, inpsTakeProfit, inpsEntry, title='S', color = red)
