//@version=3
//
// This script plots the values to be used to open long and short positions before news
// 
// Version: 1.0
// Author: Alessandra Bilardi
//
// *** You must to run backtests to define the period, news and asset where you can use it ***
// *** I'm not responsible for this script, so its using is at your own risk and danger!!  ***

strategy("Before News", overlay=true)
atr_period = input(title="ATR Range", type=integer, defval=7)
ratio = input(title="Ratio", type=float, defval=0, minval=0, maxval=78)
atr_multiple = input(title="Coverage by multiple of ATR", type=integer, defval=2, minval=0, maxval=78)
entry_position = input(title="Entry position", type=integer, defval=0, minval=-78, maxval=78)
stop_loss_position = input(title="Stop Loss position", type=integer, defval=0, minval=-78, maxval=78)
stop_loss_count = input(title="Stop Loss count by hl2 (0) or open/close (1)", type=integer, defval=0, minval=0, maxval=1)

t = tickerid(syminfo.prefix, ticker)
highT = security(t, period, high)
hl2T = security(t, period, hl2)
lowT = security(t, period, low)
openT = security(t, period, open)
closeT = security(t, period, close)

longEntry = highT + entry_position
shortEntry = lowT - entry_position

longTakeProfit = highT + ( atr(atr_period) * 2 )
longStopLoss = iff(stop_loss_count > 0, hl2T, iff(open > close, openT, closeT)) - atr(atr_period)
shortTakeProfit = lowT - ( atr(atr_period) * 2 )
shortStopLoss = iff(stop_loss_count > 0, hl2T, iff(open > close, closeT, openT)) + atr(atr_period)

ltp = plot(longTakeProfit, color=green)
le = plot(longEntry, color=gray)
lsl = plot(longStopLoss, color=red)
stp = plot(shortTakeProfit, color=blue)
se = plot(shortEntry, color=gray)
ssl = plot(shortStopLoss, color=orange)

fill(ltp, le, color=green)
fill(le, lsl, color=red)
fill(stp, se, color=blue)
fill(se, ssl, color=orange)
